### ISSUE TITLE
How to get this app ?

### ISSUE THREAD

**Issue by shabanfr** [jamestut/winwifimanager#1]
Hello guy ! I am interessing to get this app please thank you

**Comment by shabanfr** [comment]
In EXE please

**Comment by jamestut** [comment]
It is right there on the releases page.
https://github.com/jamestut/winwifimanager/releases/tag/v1.0
Download and unzip the first one and you'll get an `.exe` file.

FYI, most projects in Github have releases page. See it on the right hand side of your page. 🙂
